# Generated by Django 6.0.5 on 2026-06-25 00:57

from django.db import migrations, models


def create_default_statuses(apps, schema_editor):
    DocumentStatus = apps.get_model('documents', 'DocumentStatus')
    for code, label in [
        ('draft', 'Draft'),
        ('review', 'Under Review'),
        ('approved', 'Approved'),
        ('archived', 'Archived'),
    ]:
        DocumentStatus.objects.get_or_create(code=code, defaults={'label': label})


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Document statuses',
                'ordering': ['label'],
            },
        ),
        migrations.RunPython(create_default_statuses, migrations.RunPython.noop),
    ]
