# Generated by Django 6.0.5 on 2026-06-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
    ]
