# Generated by Django 6.0.5 on 2026-06-25 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_workflow(apps, schema_editor):
    DocumentStatus = apps.get_model('documents', 'DocumentStatus')
    statuses = {status.code: status for status in DocumentStatus.objects.all()}
    transitions = {
        'draft': ['review', 'archived'],
        'review': ['approved', 'draft', 'archived'],
        'approved': ['archived'],
        'archived': [],
    }
    for code, next_codes in transitions.items():
        status = statuses.get(code)
        if status:
            status.allowed_next_statuses.set(
                [statuses[next_code] for next_code in next_codes if next_code in statuses]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status', 'Status changed'), ('file', 'File changed'), ('comment', 'Comment added')], default='updated', max_length=20),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='allowed_next_statuses',
            field=models.ManyToManyField(blank=True, help_text='Statuses a document can move to from this status.', related_name='previous_statuses', to='documents.documentstatus'),
        ),
        migrations.CreateModel(
            name='DocumentFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/versions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(seed_default_workflow, migrations.RunPython.noop),
    ]
