# Generated by Django 6.0.5 on 2026-06-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
